# Generated by Django 3.2.9 on 2021-11-13 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broomstickAuth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='text',
        ),
    ]
