# Generated by Django 3.2.9 on 2021-11-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broomstickAuth', '0003_rename_title_note_productname'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='companyName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='note',
            name='productDescription',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='note',
            name='productName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
