# Generated by Django 3.2.9 on 2021-11-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broomstickAuth', '0004_auto_20211113_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='productImage',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
