# Generated by Django 3.2.9 on 2021-11-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broomstickAuth', '0005_note_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='productImage',
            field=models.ImageField(default='', upload_to='uploads'),
        ),
    ]
