# Generated by Django 3.2.9 on 2021-11-25 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broomstickAuth', '0006_alter_note_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='productImage',
        ),
    ]
