# Generated by Django 3.2.9 on 2022-09-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broomstickAuth', '0007_remove_note_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='featured',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='note',
            name='productImageUrl',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='note',
            name='tagline',
            field=models.CharField(default='', max_length=50),
        ),
    ]
